### PR TITLE
PEO-300 Cleanup source code

### PR DESCRIPTION
**Pull request by D3N**
[PEO-300](https://garage.atlassian.net/browse/PEO-300)

### Description

Cleanup source code

### Before submitting the merge request make sure the following are checked

- [x] Followed the style guidelines of this project
- [x] Performed a self-review of own code
- [ ] ~~Wrote the tests that prove that fix is effective/that feature works~~

### CODE REVIEW

**Comment by chubchenko** [comment]
@D3N Could you please add `Gemfile.lock` to `.gitignore`. For clarification, please see Yehuda's guidance on the roles of `.gemspec`, `Gemfile`, and `Gemfile.lock` files: [Clarifying the Roles of the .gemspec and Gemfile](https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/).
Thanks 😉

**Comment by chubchenko** [comment]
@D3N Sorry, but also will good to remove `Gemfile.lock` from the repository, thanks.

**Comment by chubchenko** [comment]
@D3N your branch has configs, can you resolve them please, thanks.

**Comment by D3N** [comment]
> @D3N your branch has configs, can you resolve them please, thanks.

@chubchenko, done

**Review by chubchenko — APPROVED** [review]

**Pull request merged**
